apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: khalil15832/angular-app:latest
          ports:
            - containerPort: 4200
